using System;
using System.Collections.Generic;
namespace ModernBoxM2Rewrite
{
    internal static partial class ContentRegistry
    {
        private static void ApplyM2EquipmentOverrides()
        {
            ApplyEquipmentOverride("AK103", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", 170f }, { "damage", 36f } });
            ApplyEquipmentOverride("AK47", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 3f }, { "attack_speed", 170f }, { "damage", 13f } });
            ApplyEquipmentOverride("Americanshotgun", "", 0, "", 0, 200, new Dictionary<string, float> { { "projectiles", 10f }, { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", -200f }, { "damage", 6f }, { "speed", 0f }, { "health", 0f }, { "accuracy", -20f }, { "range", 6f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.1f }, { "critical_damage_multiplier", 0.6f }, { "knockback", 3f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("blueblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", -40f }, { "attack_speed", 170f }, { "damage", 100f } });
            ApplyEquipmentOverride("blueblastersniper", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 40f }, { "accuracy", 5f }, { "attack_speed", -200f }, { "damage", 500f } });
            ApplyEquipmentOverride("blueheavyblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", -5000f }, { "damage", 1000f } });
            ApplyEquipmentOverride("bluelightsaber", "", 0, "", 0, 500, new Dictionary<string, float> { { "damage", 600f }, { "attack_speed", 200f }, { "damage_range", 0.1f }, { "armor", 20f } });
            ApplyEquipmentOverride("blueminigun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 10f }, { "accuracy", -50f }, { "attack_speed", 20000f }, { "damage", 30f } });
            ApplyEquipmentOverride("blueplasmagun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 8f }, { "accuracy", 90f }, { "attack_speed", 1f }, { "damage", 80f } });
            ApplyEquipmentOverride("chainsaw", "", 0, "", 0, 500, new Dictionary<string, float> { { "damage", 1000f }, { "attack_speed", 200f }, { "damage_range", 0.1f }, { "armor", 5f } });
            ApplyEquipmentOverride("Crack", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", -0.1f }, { "max_children", -5f }, { "max_age", -10f }, { "attack_speed", -20f }, { "damage", 9f }, { "speed", -5f }, { "health", -13f }, { "accuracy", 0f }, { "range", 1f }, { "armor", 4f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 2f }, { "critical_chance", 0.15f }, { "knockback", 0f }, { "knockback_reduction", 2f }, { "intelligence", -7f }, { "warfare", -4f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", -5f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("DesertEagle", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 20f }, { "accuracy", 90f }, { "attack_speed", 1f }, { "damage", 40f } });
            ApplyEquipmentOverride("FAMAS", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", 1800f }, { "damage", 13f }, { "speed", 0f }, { "health", 0f }, { "accuracy", 40f }, { "range", 14f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.0f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("futurearmor", "", 0, "", 0, 500, new Dictionary<string, float> { { "armor", 15f }, { "speed", 4f }, { "dodge", 10f }, { "health", 200f } });
            ApplyEquipmentOverride("futureboots", "", 0, "", 0, 500, new Dictionary<string, float> { { "armor", 15f }, { "speed", 4f }, { "dodge", 10f }, { "health", 200f } });
            ApplyEquipmentOverride("futurehelmet", "", 0, "", 0, 500, new Dictionary<string, float> { { "armor", 15f }, { "speed", 4f }, { "dodge", 10f }, { "health", 200f } });
            ApplyEquipmentOverride("Glock17", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 12f }, { "accuracy", -25f }, { "attack_speed", 1f }, { "damage", 35f } });
            ApplyEquipmentOverride("greenblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", -40f }, { "attack_speed", 170f }, { "damage", 100f } });
            ApplyEquipmentOverride("greenblastersniper", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 40f }, { "accuracy", 5f }, { "attack_speed", -200f }, { "damage", 500f } });
            ApplyEquipmentOverride("greenheavyblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", -5000f }, { "damage", 1000f } });
            ApplyEquipmentOverride("greenlightsaber", "", 0, "", 0, 500, new Dictionary<string, float> { { "damage", 600f }, { "attack_speed", 200f }, { "damage_range", 0.1f }, { "armor", 20f } });
            ApplyEquipmentOverride("greenminigun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 10f }, { "accuracy", -50f }, { "attack_speed", 20000f }, { "damage", 30f } });
            ApplyEquipmentOverride("greenplasmagun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 8f }, { "accuracy", 90f }, { "attack_speed", 1f }, { "damage", 80f } });
            ApplyEquipmentOverride("HK416", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 20f }, { "accuracy", 5f }, { "attack_speed", 300f }, { "damage", 60f } });
            ApplyEquipmentOverride("M16", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 0f }, { "accuracy", 5f }, { "attack_speed", 12f }, { "damage", 60f } });
            ApplyEquipmentOverride("m1garand", "", 0, "", 0, 200, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", -200f }, { "damage", 100f }, { "speed", 0f }, { "health", 0f }, { "accuracy", -20f }, { "range", 23f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.3f }, { "critical_damage_multiplier", 0.4f }, { "knockback", 1f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("M4A1", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", 100f }, { "damage", 40f } });
            ApplyEquipmentOverride("malorian", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 6f }, { "accuracy", 400f }, { "attack_speed", 70f }, { "damage", 3f } });
            ApplyEquipmentOverride("Meth", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", -0.1f }, { "max_children", -5f }, { "max_age", -10f }, { "attack_speed", 20f }, { "damage", 10f }, { "speed", 5f }, { "health", -10f }, { "accuracy", 0f }, { "range", 1f }, { "armor", 1f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 1f }, { "critical_chance", 0.15f }, { "knockback", 0f }, { "knockback_reduction", 2f }, { "intelligence", -7f }, { "warfare", -4f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("Minigun", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 10f }, { "accuracy", -40f }, { "attack_speed", 20000f }, { "projectiles", 3f }, { "damage", 13f } });
            ApplyEquipmentOverride("MIRV", "", 0, "", 0, 0, new Dictionary<string, float> { { "range", 0f }, { "accuracy", 0f }, { "attack_speed", 1f }, { "damage", 0f } });
            ApplyEquipmentOverride("MIRVBomb", "", 0, "", 0, 0, new Dictionary<string, float> { { "range", 0f }, { "accuracy", 0f }, { "attack_speed", 1f }, { "damage", 0f } });
            ApplyEquipmentOverride("modernarmor", "", 0, "", 0, 300, new Dictionary<string, float> { { "armor", 0f }, { "speed", 13f }, { "dodge", 20f }, { "attack_speed", 60f } });
            ApplyEquipmentOverride("modernboots", "", 0, "", 0, 300, new Dictionary<string, float> { { "armor", 0f }, { "speed", 13f }, { "dodge", 20f }, { "attack_speed", 60f } });
            ApplyEquipmentOverride("modernhelmet", "", 0, "", 0, 300, new Dictionary<string, float> { { "armor", 0f }, { "speed", 13f }, { "dodge", 20f }, { "attack_speed", 60f } });
            ApplyEquipmentOverride("MP7", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", -30f }, { "attack_speed", 12000f }, { "damage", 7f } });
            ApplyEquipmentOverride("Musket", "", 0, "", 0, 70, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", -200f }, { "damage", 40f }, { "speed", 0f }, { "health", 0f }, { "accuracy", -20f }, { "range", 20f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.2f }, { "critical_damage_multiplier", 0.5f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("PipePistol", "", 0, "", 0, 100, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", 20f }, { "damage", 13f }, { "speed", 0f }, { "health", 0f }, { "accuracy", 70f }, { "range", 6f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.0f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("PipeRifle", "", 0, "", 0, 100, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", 180f }, { "damage", 13f }, { "speed", 0f }, { "health", 0f }, { "accuracy", 70f }, { "range", 6f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.0f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("PipeShotgun", "", 0, "", 0, 100, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", 20f }, { "damage", 130f }, { "speed", 0f }, { "health", 0f }, { "accuracy", 70f }, { "range", 6f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.0f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("piratpistol", "", 0, "", 0, 45, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", -100f }, { "damage", 30f }, { "speed", 0f }, { "health", 0f }, { "accuracy", -20f }, { "range", 10f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.2f }, { "critical_damage_multiplier", 0.5f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("pristinearmor", "", 0, "", 0, 70, new Dictionary<string, float> { { "knockback_reduction", 1f }, { "armor", 5f }, { "speed", -5f } });
            ApplyEquipmentOverride("pristineboots", "", 0, "", 0, 70, new Dictionary<string, float> { { "knockback_reduction", 1f }, { "armor", 5f }, { "speed", -5f } });
            ApplyEquipmentOverride("pristinehelmet", "", 0, "", 0, 70, new Dictionary<string, float> { { "knockback_reduction", 1f }, { "armor", 5f }, { "speed", -5f } });
            ApplyEquipmentOverride("redblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", -40f }, { "attack_speed", 170f }, { "damage", 100f } });
            ApplyEquipmentOverride("redblastersniper", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 40f }, { "accuracy", 5f }, { "attack_speed", -200f }, { "damage", 500f } });
            ApplyEquipmentOverride("redheavyblaster", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", -5000f }, { "damage", 1000f } });
            ApplyEquipmentOverride("redlightsaber", "", 0, "", 0, 500, new Dictionary<string, float> { { "damage", 600f }, { "attack_speed", 200f }, { "damage_range", 0.1f }, { "armor", 20f } });
            ApplyEquipmentOverride("redminigun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 10f }, { "accuracy", -50f }, { "attack_speed", 20000f }, { "damage", 30f } });
            ApplyEquipmentOverride("redplasmagun", "", 0, "", 0, 500, new Dictionary<string, float> { { "range", 8f }, { "accuracy", 90f }, { "attack_speed", 1f }, { "damage", 80f } });
            ApplyEquipmentOverride("RocketLauncher", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 400f }, { "attack_speed", -5000f }, { "damage", 400f } });
            ApplyEquipmentOverride("Sandevistan", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", -0.1f }, { "max_children", 0f }, { "max_age", 10f }, { "attack_speed", 20f }, { "damage", 2f }, { "speed", 5f }, { "health", 0f }, { "accuracy", 0f }, { "range", 1f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 2f }, { "critical_chance", 0.15f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 7f }, { "warfare", 4f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("SGT44", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", 40f }, { "attack_speed", 70f }, { "damage", 11f } });
            ApplyEquipmentOverride("shieldedaxe", "", 0, "", 0, 50, new Dictionary<string, float> { { "damage", 5f }, { "attack_speed", 20f }, { "damage_range", 0.7f }, { "health", 20f }, { "armor", 10f } });
            ApplyEquipmentOverride("shieldedhammer", "", 0, "", 0, 50, new Dictionary<string, float> { { "damage", 5f }, { "attack_speed", -10f }, { "targets", 4f }, { "damage_range", 0.2f }, { "health", 20f }, { "armor", 10f } });
            ApplyEquipmentOverride("shieldedspear", "", 0, "", 0, 50, new Dictionary<string, float> { { "damage", 5f }, { "range", 2f }, { "attack_speed", 15f }, { "damage_range", 0.8f }, { "health", 20f }, { "armor", 10f } });
            ApplyEquipmentOverride("shieldedsword", "", 0, "", 0, 50, new Dictionary<string, float> { { "damage", 5f }, { "attack_speed", 20f }, { "damage_range", 0.9f }, { "health", 20f }, { "armor", 10f } });
            ApplyEquipmentOverride("Sniper", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 40f }, { "accuracy", 5f }, { "attack_speed", -200f }, { "damage", 200f } });
            ApplyEquipmentOverride("ThompsonM1A1", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 14f }, { "accuracy", -30f }, { "attack_speed", 17000f }, { "damage", 13f } });
            ApplyEquipmentOverride("TurboBooster", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", -0.1f }, { "max_children", 0f }, { "max_age", 10f }, { "attack_speed", 20f }, { "damage", 20f }, { "speed", 0f }, { "health", 10f }, { "accuracy", 0f }, { "range", 1f }, { "armor", 6f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 2f }, { "critical_chance", 0.15f }, { "knockback", 0f }, { "knockback_reduction", 2f }, { "intelligence", 7f }, { "warfare", 4f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
            ApplyEquipmentOverride("Uzi", "", 0, "", 0, 300, new Dictionary<string, float> { { "range", 6f }, { "accuracy", -10f }, { "attack_speed", 7000f }, { "damage", 5f } });
            ApplyEquipmentOverride("wwarmor", "", 0, "", 0, 200, new Dictionary<string, float> { { "armor", 0f }, { "speed", 10f }, { "dodge", 15f }, { "attack_speed", 50f } });
            ApplyEquipmentOverride("wwboots", "", 0, "", 0, 200, new Dictionary<string, float> { { "armor", 0f }, { "speed", 10f }, { "dodge", 15f }, { "attack_speed", 50f } });
            ApplyEquipmentOverride("wwhelmet", "", 0, "", 0, 200, new Dictionary<string, float> { { "armor", 0f }, { "speed", 10f }, { "dodge", 15f }, { "attack_speed", 50f } });
            ApplyEquipmentOverride("XM8", "", 0, "", 0, 300, new Dictionary<string, float> { { "fertility", 0.0f }, { "max_children", 0f }, { "max_age", 0f }, { "attack_speed", 1800f }, { "damage", 13f }, { "speed", 0f }, { "health", 0f }, { "accuracy", 400f }, { "range", 14f }, { "armor", 0f }, { "scale", 0.0f }, { "dodge", 0f }, { "targets", 0f }, { "critical_chance", 0.0f }, { "knockback", 0f }, { "knockback_reduction", 0f }, { "intelligence", 0f }, { "warfare", 0f }, { "diplomacy", 0f }, { "stewardship", 0f }, { "opinion", 0f }, { "loyalty_traits", 0f }, { "cities", 0f }, { "zone_range", 0f } });
        }
        private static void ApplyEquipmentOverride(string id, string r1, int c1, string r2, int c2, int value, Dictionary<string, float> stats)
        {
            EquipmentSpec spec = Equipment.Find(candidate => candidate.Id == id);
            if (spec == null) return;
            if (!string.IsNullOrEmpty(r1)) { spec.Resource1 = r1; spec.Resource1Cost = c1; spec.Resource2 = r2; spec.Resource2Cost = c2; }
            if (value > 0) spec.Value = value;
            if (stats == null) return;
            foreach (KeyValuePair<string, float> pair in stats) spec.BaseStats[pair.Key] = pair.Value;
            float number;
            if (stats.TryGetValue("damage", out number)) spec.Damage = number;
            if (stats.TryGetValue("range", out number)) spec.Range = number;
            if (stats.TryGetValue("attack_speed", out number)) spec.AttackSpeed = number;
            if (stats.TryGetValue("accuracy", out number)) spec.Accuracy = number;
        }
    }
}
